name: Build plugin

on:
  pull_request:
    branches: ["main"]
  release:
    types: ["published"]
  push:
    branches: ["main"]
    paths:
    - Dockerfile
    - build.json
    - 'rootfs/**' 
    - '**.go'
    - go.mod

env:
  BUILD_NAME: observer
  BUILD_TYPE: plugin

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
      version: ${{ steps.version.outputs.version }}
      channel: ${{ steps.version.outputs.channel }}
      publish: ${{ steps.version.outputs.publish }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get information
      id: info
      uses: openpeerpower/actions/helpers/info@main

    - name: Get version
      id: version
      uses: openpeerpower/actions/helpers/version@main
      with:
        type: ${{ env.BUILD_TYPE }}

  build:
    name: Build ${{ matrix.arch }} plugin
    needs: init
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
   
    - name: Login to DockerHub
      if: needs.init.outputs.publish == 'true'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set build arguments
      if: needs.init.outputs.publish == 'false'
      run: echo "BUILD_ARGS=--test" >> $GITHUB_ENV

    - name: Build plugin
      uses: openpeerpower/builder@v3.1
      with:
        args: |
          $BUILD_ARGS \
          --${{ matrix.arch }} \
          --target /data \
          --generic ${{ needs.init.outputs.version }}

  version:
    name: Update version
    needs: ["init", "build"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      if: needs.init.outputs.publish == 'true'
      uses: actions/checkout@v3

    - name: Initialize git
      if: needs.init.outputs.publish == 'true'
      uses: openpeerpower/actions/helpers/git-init@main
      with:
        name: ${{ secrets.GIT_NAME }}
        email: ${{ secrets.GIT_EMAIL }}
        token: ${{ secrets.GIT_TOKEN }}

    - name: Update version file
      if: needs.init.outputs.publish == 'true'
      uses: openpeerpower/actions/helpers/version-push@main
      with:
        key: ${{ env.BUILD_NAME }}
        version: ${{ needs.init.outputs.version }}
        channel: ${{ needs.init.outputs.channel }}
